version: '3.4'

services:
  _base:
    &base
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/code
    ports:
      - 3000:3000

  dev:
    <<: *base
    command: bash

